version: '3'

services:

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: landucci/php-laravel:prod
    container_name: nitrogenio
    networks:
      - tabela-periodica

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: landucci/nginx:prod
    container_name: fosforo
    networks:
      - tabela-periodica
    ports:
      - "8080:80"

networks:
  tabela-periodica:
    driver: bridge