version: '3'

services:

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - node

  node:
    build:
      context: node
    container_name: node
    restart: always
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on: 
      - mysql

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /docker-entrypoint-initdb.d/init-db.sql
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql/volume:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
